---
- hosts: all
  become: true
  tasks:
    - name: TZ America/Recife
      timezone:
        name: America/Recife

    # Pre-setup
    - name: Install common dependencies
      apt:
        name: '{{ packages }}'
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - net-tools

    - name: Remove buster hostname
      lineinfile:
        dest: /etc/hosts
        line: '127.0.0.2'
        regexp: '^127\.0\.0\.2'
        state: absent

    - name: Add IPv4 to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ item['ip'] }}.*$"
        line: "{{ item['ip'] }}\t\t{{ item['names'] | join(' ') }}"
        state: present
      with_items:
        - ip: 192.168.99.12
          names:
            - buster

    # Proxmox pre-setup
    - name: Add an apt signing key for PVE
      apt_key:
        url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] http://download.proxmox.com/debian/pve buster pve-no-subscription
        state: present

    - name: Install proxmox and dependencies
      apt:
        name: '{{ packages }}'
        state: present
        update_cache: yes
      vars:
        packages:
          - proxmox-ve
          - postfix
          - open-iscsi
